<template>
  <div class="col-12 color-bg-a">
    <h2>Products table</h2>
    <p>I'm gonna try to make clear how this app works, but for starting poing let's gonna supose that everything is set and running, it will be something like after the IT gut came and configure everything for you to start selling something and managing your suppliers and inventory. After that we will make speak about how to set up everything for a first time.</p>
    <p>Lets make clear how this how this supose to work with an example:<br />
      Let's say that you own a clothing store. And you have bought from your supplier a box with 10 blue Nike sleeveless shirts. Now you need to add this item to your inventory for a possible later purchase from one of your clients.</p>
      <p>That box si your ITEM, and you need to include that Item in your inventory (your database). So you go to "Items table" and you see that it asks you for "SKU" (this is just the id of the product, maybe barscode?) and that's fine. But the next three data you need to fill are this selectable input option that are empty, Product, Brand and Supplier. And we don't know what are these or why they are empty but you see that on the header you have an option called "Products table" so you click there and you get another for to create something else, not an Item this time but a Product, and this product form asks you for a title, a category and a summary (description) but how annoying! The category is also an empty selectable input data. But now you now that an Item is has a Product defined and a Product has a Category defined, and that when you keep looking the options on the header there is also a "Category table" option, so you click on it.<br />
      And this time it looks simpler, kinda, it asks you for just a title. Now, looking back you realize that an Item has a Product type and a Product has a Category so is kind of like you have two categories before your Item. So you think 'ok, I own a clothing store, but I don't sell just clothes like jeans and shirts, I have also neckless, hats, shoes, water bootles, some sunglasses' then you know what Categories mean, you know that there you can create one category for "clothes" and another one for "shoes", "jewlery" and "hats", so you do.</p>
      <p>Now that you have your categories you can go back to see what is al the Products mambo jumbo about. And it's weird because if you already have a category defined for your Item why do you need a Product for it too? This Items I've just got are Shirts, they are just clothes! But then you look at your self and you realize that you are wearing a shirt too... but your shirt is differnt, yours HAS sleeves...mmmmm... is like a similar Item but different, you realize that you could say that "is a similar Product but a different Item", that's it!<br />
      Now you can create your Product, with your title like "Sleeveless shirt". Then you see your Category option, you click on it and you can see how now is displaying clothes, shoes, jewlery and hats, then you know you got it, you just chose "clothes", then you can add a description of the PRODUCT, remember that is a product, not an Item. This description would be a tool just for you, for you to know what type of product you meant when you said "Sleeveless shirt" so you write "Normal light shirt with now sleeves" then you realize that there exists more than one type of sleevless shirts, there are formal ones and other more informal like for trayinging or for the beach, but you will take care of that later, after all you see that just there there is a "pencil" icon that looks like something for editing your Products and Categories.</p>
      <p>Now you are back on your Item, but you realize that you have your Category, you have your Product, but there are two more things, Brand and Supplier. But you already now what to do with that. You know your supplier, you have it's data (phone, address, person in charge, office address...) and you know the brand of the shirts you have there (Nike).<br />
      So following the workflow you search for a "Brands table" between the headers options and it's there! So you click it you fill the title and so on. Then you look for the next one "Suppliers table" and it's also there! This one asks for much more but the only required field is title for defining the supplier, you can always later come back to add more data to it, you just save the title for now like "My supplier"</p>
      <p>Finally you can go back to your "Items table" give the identification for it (sku), give your "Sleeveless shirt" (product), the "Nike" (Brand) and the "My supplier" (supplier) and save it.</p>
  </div>
</template>

<script>
export default {
}
</script>
